# Generated by Django 4.1 on 2022-08-28 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videoupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='VideoDetailModel',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/')),
                ('video', models.FileField(upload_to='video/')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoupload.videocategorymodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
