# Generated by Django 4.1 on 2022-08-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_videocategorymodel_videodetailmodel_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetailmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='videodetailmodel',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='VideoCategoryModel',
        ),
    ]
