# Generated by Django 4.1 on 2022-08-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0003_remove_videodetailmodel_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='SOME STRING', max_length=20)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AddField(
            model_name='videodetailmodel',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='videoupload.videocategorymodel'),
        ),
    ]
